VikoServiceManager/Models/ResidentGroup.cs
namespace VikoServiceManager.Models
{
    public class ResidentGroup
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
    }
}

VikoServiceManager/Models/ResidentGroupViewModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VikoServiceManager.Models
{
    public class ResidentGroupViewModel
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public string? Description { get; set; }
        [NotMapped]
        public float? ServicePrice { get; set; }
    }
}

VikoServiceManager/Controllers/ResidentGroupController.cs
using IdentityManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using System.Text.RegularExpressions;
using VikoServiceManager.Models;

namespace VikoServiceManager.Controllers
{
    [Authorize]
    public class ResidentGroupController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ResidentGroupController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: ResidentGroupController
        public IActionResult Index()
        {
            var groupsObj = _db.ResidentGroup.ToList();
            var test = _db.HouseService.ToList();
            foreach (var group in groupsObj)
            {
                var houseObj = _db.House.FirstOrDefault(u => u.ResidentGroup == group);
                if (houseObj != null)
                {
                    var houseServiceObj = _db.HouseService.Where(u => u.House.Id == houseObj.Id).Select(i => i.Service);

                    if (houseServiceObj != null)
                    {
                        group.ServicePrice = houseServiceObj.Select(u => u.Price).FirstOrDefault();
                    }
                    else
                    {
                        group.ServicePrice = 0;
                    }
                }
                else
                {
                    group.ServicePrice = 0;
                }

            }
            return View(groupsObj);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Upsert(string id)
        {
            if (String.IsNullOrEmpty(id))
            {
                return View();
            }
            else
            {
                // update
                var objFromDb = _db.Service.FirstOrDefault(x => x.Id.Equals(id));
                return View(objFromDb);
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(ResidentGroupViewModel residentGroup)
        {

            if (_db.Service.Any(u => u.ServiceName == residentGroup.Name))
            {
                //error
                TempData[SD.Error] = "Resident group already exists!";
                return RedirectToAction(nameof(Index));
            }
            if (string.IsNullOrEmpty(Convert.ToString(residentGroup.Id)) || residentGroup.Id == 0)
            {
                //create
                _db.ResidentGroup.Add(new ResidentGroupViewModel() { Name = residentGroup.Name, Description = residentGroup.Description });
                _db.SaveChanges();
                TempData[SD.Success] = "Resident group created successfully!";
            }
            /*            else
                        {
                            // update
                            var objRoleFromDb = _db.Roles.FirstOrDefault(u => u.Id == serviceObj.Id);
                            if (objRoleFromDb == null)
                            {
                                TempData[SD.Error] = "Role not found!";
                                return RedirectToAction(nameof(Index));
                            }
                            objRoleFromDb.Name = serviceObj.ServiceName;
                            objRoleFromDb.NormalizedName = serviceObj.ServiceName.ToUpper();
                            var result = await _roleManager.UpdateAsync(objRoleFromDb);
                            TempData[SD.Success] = "Role updated successfully!";
                        }*/
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int userId)
        {
            var objFromDb = _db.ResidentGroup.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                // error Resident Grouop not found
                TempData[SD.Error] = "Resident Group not found!";
                return RedirectToAction(nameof(Index));
            }

            var userGroupsForThisHouse = _db.ResidentGroupMembership.Where(u => u.ResidentGroup.Id == userId).Count();
            if (userGroupsForThisHouse > 0)
            {
                TempData[SD.Error] = "Cannot delete this service, since there are house assigned for this service!";
                return RedirectToAction(nameof(Index));
            }
            _db.ResidentGroup.Remove(objFromDb);
            _db.SaveChanges();
            TempData[SD.Success] = "Resident Group deleted successfully!";

            return RedirectToAction(nameof(Index));
        }
    }
}

VikoServiceManager/Views/ResidentGroup/Index.cshtml
@model IEnumerable<ResidentGroupViewModel>
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Resident Group List</h2>
    </div>
    @if (ViewContext.HttpContext.User.IsInRole("Admin"))
    {
        <div class="col-6">
            <a asp-action="Upsert" asp-asp-controller="ResidentGroup" class="btn btn-primary float-end">Create New Resident Group</a>
        </div>
    }
</div>
<div class="p-4 border rounded">
    @if (Model.Any())
    {
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Sum of all Services
                </th>
                    <th>
                    </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Id
                    </td>
                    <td>
                        @item.Name
                    </td>
                    <td>
                        @item.Description
                    </td>
                    <td >
                        @item.ServicePrice€
                    </td>
                    <th>
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <div class="text-center">
                                <form asp-action="Delete" asp-route-userId="@item.Id">
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete this?')" class="btn btn-danger">
                                        Delete
                                    </button>
                                </form>
                            </div>
                        }
                    </th>
                </tr>
            }
        </table>
    }
</div>

VikoServiceManager/Views/ResidentGroup/Upsert.cshtml
@model ResidentGroupViewModel

@{
    var title = "Create Resident Group";
}

<form method="post">
    <input asp-for="@Model.Id" hidden />
    @if (Model != null && !String.IsNullOrEmpty(Convert.ToString(Model.Id)))
    {
        title = "Edit Create Resident Group";
    }

    <div class="border p-3 bg-white">
        <div class="form-group row">
            <h2 class="text-info pl-3">@title</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Id" readonly class="form-control"></input>
                    </div>
                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control"></input>
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row py-2">
                    <div class="col-4">
                        <label asp-for="Description"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Description" class="form-control"></input>
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row py-2">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            @if (Model != null && !String.IsNullOrEmpty(Convert.ToString(Model.Id)))
                            {
                            //update
                                <input type="submit" class="btn btn-primary w-100" value="Update" />
                            }
                            else
                            {
                                // create
                                <input type="submit" class="btn btn-primary w-100" value="Create" />
                            }
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>