VikoServiceManager/Controllers/HouseController.cs
using Azure.Core;
using IdentityManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;
using VikoServiceManager.Models;

namespace VikoServiceManager.Controllers
{
    [Authorize]
    public class HouseController : Controller
    {
        private readonly ApplicationDbContext _db;

        public HouseController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(int id)
        {

            var houseList = _db.House.ToList();

            var houseServiceList = _db.HouseService.ToList();
            var serviceList = _db.Service.ToList();


            var residentGroups = _db.ResidentGroup.ToList();
            foreach (var house in houseList)
            {
                if (house != null && house.ResidentGroup != null)
                {
                    house.ResidentGroupName = residentGroups.FirstOrDefault(u => u.Id == house.ResidentGroup.Id).Name;
                }
                else
                {
                    house.ResidentGroupName = "None";
                }

                var service = houseServiceList.FirstOrDefault(u => u.House.Id.Equals(house.Id));
                if (service == null)
                {
                    house.ServiceName = "None";
                }
                else
                {
                    house.ServiceName = service.Service.ServiceName;
                }
            }
            return View(houseList);
        }

        [HttpGet]
        public IActionResult Upsert(int houseId)
        {
            // Create list for select element
            var resGroupFromDb = _db.ResidentGroup.ToList();
            var serviceFromDb = _db.Service.ToList();

            List<SelectListItem> groupsItems = new List<SelectListItem>();
            foreach (var item in resGroupFromDb)
            {
                groupsItems.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                });
            }

            List<SelectListItem> servcieItems = new List<SelectListItem>();
            foreach (var item in serviceFromDb)
            {
                servcieItems.Add(new SelectListItem()
                {
                    Text = item.ServiceName,
                    Value = item.Id.ToString()
                });
            }

            HouseViewModel houseViewModel = new HouseViewModel()
            {
                ResidentGroupList = groupsItems,
                ServiceSelectedList = servcieItems

            };

            if (String.IsNullOrEmpty(Convert.ToString(houseId)) || houseId == 0)
            {
                return View(houseViewModel);
            }
            else
            {
                // update               
                var objFromDb = _db.House.FirstOrDefault(x => x.Id == houseId);
                objFromDb.ResidentGroupList = houseViewModel.ResidentGroupList;
                objFromDb.ServiceSelectedList = houseViewModel.ServiceSelectedList;
                return View(objFromDb);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(HouseViewModel houseObj)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(Convert.ToString(houseObj.Id)) || houseObj.Id == 0)
                {
                    //create
                    var objGroupFromDb = _db.ResidentGroup.FirstOrDefault(u => u.Id.ToString() == houseObj.ResidentGroupSelected);
                    _db.House.Add(new HouseViewModel()
                    {
                        Address = houseObj.Address,
                        City = houseObj.City,
                        Region = houseObj.Region,
                        PostalCode = houseObj.PostalCode,
                        ResidentGroup = objGroupFromDb,

                    });
                    _db.SaveChanges();
                    TempData[SD.Success] = "House Entry created successfully!";
                }
                else
                {


                    // update
                    var objHouseFromDb = _db.House.FirstOrDefault(u => u.Id == houseObj.Id);
                    var objGroupFromDb = _db.ResidentGroup.FirstOrDefault(u => u.Id.ToString() == houseObj.ResidentGroupSelected);
                    var objServiceFromDb = _db.Service.FirstOrDefault(u => u.Id.ToString() == houseObj.ServiceSelected);
                    if (objHouseFromDb == null)
                    {
                        TempData[SD.Error] = "Role not found!";
                        return RedirectToAction(nameof(Index));
                    }
                    objHouseFromDb.Address = houseObj.Address;
                    objHouseFromDb.City = houseObj.City;
                    objHouseFromDb.Region = houseObj.Region;
                    objHouseFromDb.PostalCode = houseObj.PostalCode;
                    objHouseFromDb.ResidentGroup = objGroupFromDb;


                    if (objServiceFromDb != null)
                    {
                        // delete servcie if it already exists
                        var houseService = _db.HouseService.FirstOrDefault(u => u.House.Id == objHouseFromDb.Id); // association between house and service
                        if (houseService != null)
                        {
                            _db.HouseService.Remove(houseService);
                        }
                        _db.HouseService.Add(new HouseServiceViewModel()
                        {
                            House = objHouseFromDb,
                            Service = objServiceFromDb
                        });
                    }

                    _db.House.Update(objHouseFromDb);
                    _db.SaveChanges();

                    TempData[SD.Success] = "House updated successfully!";
                }
                return RedirectToAction(nameof(Index));
            }
            return View(houseObj);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int houseId)
        {
            var objFromDb = _db.House.FirstOrDefault(u => u.Id == houseId);
            if (objFromDb == null)
            {
                TempData[SD.Error] = "Service not found!";
                return RedirectToAction(nameof(Index));
            }
            _db.House.Remove(objFromDb);
            _db.SaveChanges();
            TempData[SD.Success] = "House deleted successfully!";

            return RedirectToAction(nameof(Index));
        }

    }
}

VikoServiceManager/Controllers/UserController.cs
using IdentityManager.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using VikoServiceManager.Data;
using VikoServiceManager.Models;

namespace VikoServiceManager.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        // dependency injection for DB and IdentityUser
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> _userManager;

        public UserController(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            var userList = _db.ApplicationUser.ToList();
            var userRole = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();
            foreach (var user in userList)
            {
                var role = userRole.FirstOrDefault(u => u.UserId == user.Id);
                if (role == null)
                {
                    user.Role = "None";
                }
                else
                {
                    user.Role = roles.FirstOrDefault(u => u.Id == role.RoleId).Name;
                }
            }
            return View(userList);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(string userId)
        {
            var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId); // getting user object from database
            if (objFromDb == null)
            {
                return NotFound();
            }

            var userRole = _db.UserRoles.ToList(); // association between user and role
            var roles = _db.Roles.ToList(); // association between user and role

            var role = userRole.FirstOrDefault(u => u.UserId == objFromDb.Id); // we check if that role was assigned to that user

            if (role != null)
            {
                objFromDb.RoleId = roles.FirstOrDefault(u => u.Id == role.RoleId).Id;
            }

            objFromDb.RoleList = _db.Roles.Select(u => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = u.Name,
                Value = u.Id
            });
            return View(objFromDb);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ApplicationUser user)
        {
            if (ModelState.IsValid)
            {
                var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == user.Id); // getting user object from database
                if (objFromDb == null)
                {
                    return NotFound();
                }

                var userRole = _db.UserRoles.FirstOrDefault(u => u.UserId == objFromDb.Id); // association between user and role
                if (userRole != null)
                {
                    var previousRoleName = _db.Roles.Where(u => u.Id == userRole.RoleId).Select(e => e.Name).FirstOrDefault();
                    //removing old role
                    await _userManager.RemoveFromRoleAsync(objFromDb, previousRoleName);
                }

                //add new role
                await _userManager.AddToRoleAsync(objFromDb, _db.Roles.FirstOrDefault(u => u.Id == user.RoleId).Name);
                //update name
                objFromDb.Name = user.Name;
                _db.SaveChanges();
                TempData[SD.Success] = "User has been edited successfully.";
                return RedirectToAction(nameof(Index));
            }

            user.RoleList = _db.Roles.Select(u => new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
            {
                Text = u.Name,
                Value = u.Id
            });
            return View(user);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult LockUnlock(string userId)
        {
            var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            // checks if user lockout is not null and if it is set greater than today
            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                // then we ulnock user 
                objFromDb.LockoutEnd = DateTime.Now;
                TempData[SD.Success] = "User unlocked successfully.";
            }
            else
            {
                // user is not locked and we want to lock it
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
                TempData[SD.Success] = "User locked successfully.";
            }
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(string userId)
        {
            var objFromDb = _db.ApplicationUser.FirstOrDefault(u => u.Id == userId);
            if (objFromDb == null)
            {
                return NotFound();
            }
            _db.ApplicationUser.Remove(objFromDb);
            _db.SaveChanges();
            TempData[SD.Success] = "User deleted successfully.";

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user == null) 
            {
                return NotFound();
            }

            var existingUserClaims = await _userManager.GetClaimsAsync(user);

            // based on user id we create view model for claims
            var model = new UserClaimsViewModel()
            {
                UserId = userId,
            };

            // creating user claims and adding them to our model
            foreach (var claim in ClaimStore.claimsList)
            {
                UserClaim userClaim = new UserClaim()
                {
                    ClaimType = claim.Type,
                };
                if (existingUserClaims.Any(c => c.Type == claim.Type))
                {
                    userClaim.IsSelected = true;    
                }
                model.Claims.Add(userClaim);
            }
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> ManageUserClaims(UserClaimsViewModel userClaimsViewModel)
        {
            IdentityUser user = await _userManager.FindByIdAsync(userClaimsViewModel.UserId);
            if (user == null)
            {
                return NotFound();
            }

            var claims = await _userManager.GetClaimsAsync(user);
            var result = await _userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                TempData[SD.Error] = "Error while removing claims.";
                return View(userClaimsViewModel);
            }

            result = await _userManager.AddClaimsAsync(user, 
                userClaimsViewModel.Claims.Where(c => c.IsSelected).Select(c => new Claim(c.ClaimType, c.IsSelected.ToString()))
                );

            if (!result.Succeeded)
            {
                TempData[SD.Error] = "Error while removing claims.";
                return View(userClaimsViewModel);
            }

            TempData[SD.Success] = "Claims updated successfully.";

            return RedirectToAction(nameof(Index));
        }
    }
}

VikoServiceManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VikoServiceManager</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/css/bootstrap.min.css" integrity="sha512-6KY5s6UI5J7SVYuZB4S/CZMyPylqyyNZco376NM2Z8Sb8OxEdp02e1jkKk/wZxIEmjQ6DRCEBhni+gpr9c4tvA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/VikoServiceManager.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" crossorigin="anonymous" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VikoServiceManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("Manager") || ViewContext.HttpContext.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ResidentGroup" asp-action="Index">Resident Groups</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="House" asp-action="Index">House List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ResidentMembership" asp-action="Index">Resident Membership List</a>
                            </li>
                        }
                        @if (ViewContext.HttpContext.User.IsInRole("Manager") || ViewContext.HttpContext.User.IsInRole("Admin") || ViewContext.HttpContext.User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Service" asp-action="Index">Services List</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VikoServiceManager by Giedrius Mauza
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.1/js/bootstrap.min.js" integrity="sha512-ewfXo9Gq53e1q1+WDTjaHAGZ8UvCWq0eXONhwDuIoaH8xz2r96uoAYaQCm1oQhnBfRXrvJztNXFsTloJfgbL5Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VikoServiceManager/Views/Shared/_LoginPartialCustom.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <a class="nav-link" href="">Hello @UserManager.GetUserName(User)</a>
        </li>
        <li class="nav-item">
            <form id="logoutForm" method="post" class="form-inline" asp-controller="Account" asp-action="LogOff">
                <button type="submit" class="btn nav-link">Logout</button>
            </form>
            
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
        </li>
    }
    
</ul>

VikoServiceManager/Views/Shared/_Notification.cshtml
@if (TempData[SD.Success] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[SD.Success]');
    </script>
}
@if (TempData[SD.Error] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[SD.Error]');
    </script>
}